# fail_fast: true
default_stages:
  - "commit"
  
repos:
- repo: https://github.com/PyCQA/autoflake
  # autoflake removes unused import statements, config in args below
  rev: v2.3.1
  hooks:
    - id: autoflake
      args: ['--in-place', '--remove-all-unused-imports', '--ignore-init-module-imports']

- repo: https://github.com/pre-commit/mirrors-isort
  # isort sorts the import statements, config file pyproject.toml
  rev: v5.10.1
  hooks:
    - id: isort
      args: ["--profile", "black", "--filter-files"]

- repo: https://github.com/ambv/black
  # black formats the code, config file pyproject.toml
  rev: 22.3.0
  hooks:
    - id: black
      language_version: python3

- repo: https://github.com/pre-commit/mirrors-mypy
  # To enforce type hinting
  rev: v0.981
  hooks:
  -   id: mypy
      # This setting is not that strict: see https://mypy.readthedocs.io/en/stable/config_file.html for more config options.
      exclude: (setup)|(tests)|(docs)
      additional_dependencies:
        - "types-PyYAML"

- repo: https://github.com/PyCQA/flake8.git
  # Check code style
  rev: '7.0.0'
  hooks:
    - id: flake8
      additional_dependencies:
        - flake8-docstrings
        - flake8-pyproject

- repo: https://github.com/jsh9/pydoclint
  # Check docstrings for consistency with code.
  rev: '0.3.8'
  hooks:
    - id: pydoclint

- repo: local
  hooks:
  - id: unittest
  # todo: reuse test environment!
    name: unittest
    entry: 'make test-unit'
    language: system
    types: [python]
    verbose: true
    pass_filenames: false
    stages:
      - "push"
